version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: dotnet/corert
  reviewers:
  - acid-chicken
  assignees:
  - acid-chicken
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: dotnet/sdk
  reviewers:
  - acid-chicken
  assignees:
  - acid-chicken
